
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Project(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,
	
	output[9:0]						LED
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

nios(.clk_clk(CLOCK_50), .reset_reset_n(1'b1), .mm_conduit_export(LED[7:0]));


endmodule
